# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46507cc28c44f24ba47629be63d488b6238791d635cd04f15e023f6c3840e63096c666ff1af43f942b92b394589cfbdce8a74cb2d55d49ba6c8049e5cb9fa1f3

test:
  secret_key_base: a40685efb6bc1fffc8a0dc44fe7451b04abc07ae6a74f4632348c769664d3b0fb9ccd3924342641f3e8a7119a8014ea08963f92c96b11dfa0ecf578f06ea516d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
