#theme_advanced_toolbar_location: top
#theme_advanced_toolbar_align: left
#theme_advanced_statusbar_location: bottom
#theme_advanced_resizing: true

#plugins:
#  - autolink
#  - lists
#  - spellchecker
#  - pagebreak
#  - style
#  - layer
#  - table
#  - save
#  - advhr
#  - advimage
#  - advlink
#  - emotions
#  - iespell
#  - inlinepopups
#  - insertdatetime
#  - preview
#  - media
#  - searchreplace
#  - print
#  - contextmenu
#  - paste
#  - directionality
#  - fullscreen
#  - noneditable
#  - visualchars
#  - nonbreaking
#  - xhtmlxtras
#  - template
#
#theme_advanced_buttons1_add:
#  - save,newdocument
#  - '|'
#  - bold
#  - italic
#  - underline
#  - strikethrough
#  - '|'
#  - justifyleft
#  - justifycenter
#  - justifyright
#  - justifyfull
#  - '|'
#  - styleselect
#  - formatselect
#  - fontselect
#  - fontsizeselect
#theme_advanced_buttons2_add:
#  - cut
#  - copy
#  - paste
#  - pastetext
#  - pasteword
#  - '|'
#  - search
#  - replace
#  - '|'
#  - bullist
#  - numlist
#  - '|'
#  - outdent
#  - indent
#  - blockquote
#  - '|'
#  - undo
#  - redo
#  - '|'
#  - link
#  - unlink
#  - anchor
#  - image
#  - cleanup
#  - help
#  - code
#  - '|'
#  - insertdate
#  - inserttime
#  - preview
#  - '|'
#  - forecolor
#  - backcolor
#theme_advanced_buttons3_add:
#  - tablecontrols
#  - '|'
#  - hr
#  - removeformat
#  - visualaid
#  - '|'
#  - sub
#  - sup
#  - '|'
#  - charmap
#  - emotions
#  - iespell
#  - media
#  - advhr
#  - '|'
#  - print
#  - '|'
#  - ltr
#  - rtl
#  - '|'
#  - fullscreen
#theme_advanced_buttons4_add:
#  - insertlayer
#  - moveforward
#  - movebackward
#  - absolute
#  - '|'
#  - styleprops
#  - spellchecker
#  - '|'
#  - cite
#  - abbr
#  - acronym
#  - del
#  - ins
#  - attribs
#  - '|'
#  - visualchars
#  - nonbreaking
#  - template
#  - blockquote
#  - pagebreak
#  - '|'
#  - insertfile
#  - insertimage